<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\AgriDrone.SharedKernel\AgriDrone.SharedKernel.csproj" />
    <ProjectReference Include="..\AgriDrone.SharedInfrastructure\AgriDrone.SharedInfrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\AgriDrone.Modules.Identity\AgriDrone.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\Modules\AgriDrone.Modules.Farms\AgriDrone.Modules.Farms.csproj" />
    <ProjectReference Include="..\..\Modules\AgriDrone.Modules.Plants\AgriDrone.Modules.Plants.csproj" />
    <ProjectReference Include="..\..\Modules\AgriDrone.Modules.Missions\AgriDrone.Modules.Missions.csproj" />
    <ProjectReference Include="..\..\Modules\AgriDrone.Modules.Harvests\AgriDrone.Modules.Harvests.csproj" />
    <ProjectReference Include="..\..\Modules\AgriDrone.Modules.FieldTasks\AgriDrone.Modules.FieldTasks.csproj" />
    <ProjectReference Include="..\..\Modules\AgriDrone.Modules.Notifications\AgriDrone.Modules.Notifications.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" />
  </ItemGroup>
</Project>
