<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\AgriDrone.SharedKernel\AgriDrone.SharedKernel.csproj" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="MediatR" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
	</ItemGroup>
	
</Project>
